version: 2.1

orbs:
  docker: circleci/docker@x.y.z

jobs:
  check-and-build-only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: ebramhome/taplist:development
workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only